import { Milestone } from "../types/milestones";

export const MILESTONES_DATA: Milestone[] = [
  // Faith
  {
    pillar: "Faith",
    title: "Seeker of Light",
    description: "1 day of spiritual habit",
    daysRequired: 1,
    completed: false,
  },
  {
    pillar: "Faith",
    title: "Heart Aligned",
    description: "3 days of spiritual habit",
    daysRequired: 3,
    completed: false,
  },
  {
    pillar: "Faith",
    title: "Spirit Anchored",
    description: "5 days of spiritual habit",
    daysRequired: 5,
    completed: false,
  },
  {
    pillar: "Faith",
    title: "Faithful Flame",
    description: "7 days of spiritual habit",
    daysRequired: 7,
    completed: false,
  },
  {
    pillar: "Faith",
    title: "Devoted Soul",
    description: "10 days of spiritual habit",
    daysRequired: 10,
    completed: false,
  },
  {
    pillar: "Faith",
    title: "Covenant Walker",
    description: "14 days of spiritual habit",
    daysRequired: 14,
    completed: false,
  },
  {
    pillar: "Faith",
    title: "Unshaken Spirit",
    description: "21 days of spiritual habit",
    daysRequired: 21,
    completed: false,
  },
  {
    pillar: "Faith",
    title: "Sanctified Life",
    description: "30 days of spiritual habit",
    daysRequired: 30,
    completed: false,
  },

  // Discipline
  {
    pillar: "Discipline",
    title: "Iron Start",
    description: "1 day of completing hard discipline task",
    daysRequired: 1,
    completed: false,
  },
  {
    pillar: "Discipline",
    title: "Habit Spark",
    description: "3 days of discipline-based habit",
    daysRequired: 3,
    completed: false,
  },
  {
    pillar: "Discipline",
    title: "Routine Initiate",
    description: "5 days of discipline-based habit",
    daysRequired: 5,
    completed: false,
  },
  {
    pillar: "Discipline",
    title: "No Days Off",
    description: "7 days of discipline-based habit",
    daysRequired: 7,
    completed: false,
  },
  {
    pillar: "Discipline",
    title: "Momentum Builder",
    description: "10 days of discipline-based habit",
    daysRequired: 10,
    completed: false,
  },
  {
    pillar: "Discipline",
    title: "Relentless Drive",
    description: "14 days of discipline-based habit",
    daysRequired: 14,
    completed: false,
  },
  {
    pillar: "Discipline",
    title: "The Unbroken",
    description: "21 days of discipline-based habit",
    daysRequired: 21,
    completed: false,
  },
  {
    pillar: "Discipline",
    title: "Discipline Mastery",
    description: "30 days of discipline-based habit",
    daysRequired: 30,
    completed: false,
  },

  // Focus
  {
    pillar: "Focus",
    title: "Clarity Kickoff",
    description: "1 day of focused work",
    daysRequired: 1,
    completed: false,
  },
  {
    pillar: "Focus",
    title: "Zero Drift",
    description: "3 days of deep work habits",
    daysRequired: 3,
    completed: false,
  },
  {
    pillar: "Focus",
    title: "Mind Sharpener",
    description: "5 days of focus tasks",
    daysRequired: 5,
    completed: false,
  },
  {
    pillar: "Focus",
    title: "Flow Initiate",
    description: "7 days of focused practice",
    daysRequired: 7,
    completed: false,
  },
  {
    pillar: "Focus",
    title: "Time Locker",
    description: "10 days of focused habits",
    daysRequired: 10,
    completed: false,
  },
  {
    pillar: "Focus",
    title: "Mental Edge",
    description: "14 days of focused work",
    daysRequired: 14,
    completed: false,
  },
  {
    pillar: "Focus",
    title: "Distraction Slayer",
    description: "21 days of focus tasks",
    daysRequired: 21,
    completed: false,
  },
  {
    pillar: "Focus",
    title: "Laser Vision",
    description: "30 days of focused habits",
    daysRequired: 30,
    completed: false,
  },

  // Fitness
  {
    pillar: "Fitness",
    title: "Vital Spark",
    description: "1 day of fitness-related activity",
    daysRequired: 1,
    completed: false,
  },
  {
    pillar: "Fitness",
    title: "Body in Motion",
    description: "3 days of physical fitness habits",
    daysRequired: 3,
    completed: false,
  },
  {
    pillar: "Fitness",
    title: "Energy Flow",
    description: "5 days of fitness habits",
    daysRequired: 5,
    completed: false,
  },
  {
    pillar: "Fitness",
    title: "Fitness Builder",
    description: "7 days of body practices",
    daysRequired: 7,
    completed: false,
  },
  {
    pillar: "Fitness",
    title: "Stamina Boost",
    description: "10 days of fitness habits",
    daysRequired: 10,
    completed: false,
  },
  {
    pillar: "Fitness",
    title: "Resilience Rising",
    description: "14 days of fitness practice",
    daysRequired: 14,
    completed: false,
  },
  {
    pillar: "Fitness",
    title: "Endurance Mode",
    description: "21 days of body practice",
    daysRequired: 21,
    completed: false,
  },
  {
    pillar: "Fitness",
    title: "Peak State",
    description: "30 days of fitness-focused habits",
    daysRequired: 30,
    completed: false,
  },

  // Wisdom
  {
    pillar: "Wisdom",
    title: "Knowledge Spark",
    description: "1 day of learning habit",
    daysRequired: 1,
    completed: false,
  },
  {
    pillar: "Wisdom",
    title: "Thought Builder",
    description: "3 days of learning habit",
    daysRequired: 3,
    completed: false,
  },
  {
    pillar: "Wisdom",
    title: "Skill Apprentice",
    description: "5 days of learning",
    daysRequired: 5,
    completed: false,
  },
  {
    pillar: "Wisdom",
    title: "Mental Climber",
    description: "7 days of wisdom habits",
    daysRequired: 7,
    completed: false,
  },
  {
    pillar: "Wisdom",
    title: "Growth Seeker",
    description: "10 days of knowledge habits",
    daysRequired: 10,
    completed: false,
  },
  {
    pillar: "Wisdom",
    title: "Sage in Training",
    description: "14 days of learning",
    daysRequired: 14,
    completed: false,
  },
  {
    pillar: "Wisdom",
    title: "Mind Ascending",
    description: "21 days of wisdom-related activity",
    daysRequired: 21,
    completed: false,
  },
  {
    pillar: "Wisdom",
    title: "Wisdom Mastery",
    description: "30 days of consistent learning",
    daysRequired: 30,
    completed: false,
  },

  // Finance
  {
    pillar: "Finance",
    title: "Money Minded",
    description: "1 day of financial habit",
    daysRequired: 1,
    completed: false,
  },
  {
    pillar: "Finance",
    title: "Budget Initiate",
    description: "3 days of financial habit",
    daysRequired: 3,
    completed: false,
  },
  {
    pillar: "Finance",
    title: "Wealth Builder",
    description: "5 days of financial habit",
    daysRequired: 5,
    completed: false,
  },
  {
    pillar: "Finance",
    title: "Smart Earner",
    description: "7 days of financial habit",
    daysRequired: 7,
    completed: false,
  },
  {
    pillar: "Finance",
    title: "Money Alchemist",
    description: "10 days of financial habit",
    daysRequired: 10,
    completed: false,
  },
  {
    pillar: "Finance",
    title: "Strategic Saver",
    description: "14 days of financial habit",
    daysRequired: 14,
    completed: false,
  },
  {
    pillar: "Finance",
    title: "Financial Warrior",
    description: "21 days of financial habit",
    daysRequired: 21,
    completed: false,
  },
  {
    pillar: "Finance",
    title: "Master of Money",
    description: "30 days of consistent financial habits",
    daysRequired: 30,
    completed: false,
  },
];
