import { Habit } from "../types/habit";

export const MOCK_DATA: (Habit & { emoji: string })[] = [
  {
    id: Date.now().toString() + "-2",
    name: "Read 10 Pagesx",
    createDate: Date.now().toString(),
    completed: true,
    streak: 3,
    difficulty: "Medium",
    repeat: "EveryDay",
    category: "Wisdom",
    emoji: "📘",
  },
  {
    id: Date.now().toString() + "-3",
    name: "No Sugar",
    createDate: Date.now().toString(),
    completed: false,
    streak: 1,
    difficulty: "Hard",
    repeat: "EveryDay",
    category: "Discipline",
    emoji: "❌",
  },
  {
    id: Date.now().toString() + "-4",
    name: "Prayer",
    createDate: Date.now().toString(),
    completed: true,
    streak: 12,
    difficulty: "Easy",
    repeat: "EveryDay",
    category: "Faith",
    emoji: "🙏",
  },
  {
    id: Date.now().toString() + "-5",
    name: "Cold Shower",
    createDate: Date.now().toString(),
    completed: false,
    streak: 2,
    difficulty: "Hard",
    repeat: "EveryDay",
    category: "Health",
    emoji: "🛁",
  },
  {
    id: Date.now().toString() + "-6",
    name: "Journal",
    createDate: Date.now().toString(),
    completed: true,
    streak: 5,
    difficulty: "Easy",
    repeat: "EveryDay",
    category: "Focus",
    emoji: "📝",
  },
  {
    id: Date.now().toString() + "-7",
    name: "Deep Work",
    createDate: Date.now().toString(),
    completed: false,
    streak: 4,
    difficulty: "Medium",
    repeat: "EveryDay",
    category: "Focus",
    emoji: "🎯",
  },
  {
    id: Date.now().toString() + "-8",
    name: "Stretching",
    createDate: Date.now().toString(),
    completed: false,
    streak: 0,
    difficulty: "Easy",
    repeat: "EveryDay",
    category: "Health",
    emoji: "🧘",
  },
  {
    id: Date.now().toString() + "-9",
    name: "Meditation",
    createDate: Date.now().toString(),
    completed: true,
    streak: 6,
    difficulty: "Medium",
    repeat: "EveryDay",
    category: "Wisdom",
    emoji: "🧠",
  },
  {
    id: Date.now().toString() + "-10",
    name: "Wake Up at 6AM",
    createDate: Date.now().toString(),
    completed: false,
    streak: 7,
    difficulty: "Hard",
    repeat: "EveryDay",
    category: "Discipline",
    emoji: "⏰",
  },
];
